### PR TITLE
Fix Issue #86: Infinite Loop for Cross Site Sub-directory Sites

### LINKED ISSUE #86: Infinite loop for sub-directory sites
When trying to log into a sub-directory site like:

https://www.example.com/subsite/wp-login.php?redirect_to=https://www.exmaple.com/subsite/

I'm getting an infinite loop. The base url is submitting to itself. That is the cross site form on www.example.com/sso/verify is submitting to www.example.com/sso/verify instead of submitting to www.example.com/subsite/sso/verify. The $sso_url [here](https://github.com/humanmade/wp-simple-saml/blob/87d1d1e48c717aaba4196fcd688fb856d5494189/inc/namespace.php#L657) is being set incorrectly for sub-directory sites.

### PR DESCRIPTION
**Pull request by clonge**
Fixes #86

### CODE REVIEW

File: inc/namespace.php [hunk 1]
```diff
@@ -652,9 +652,7 @@ function cross_site_sso_redirect( $url ) {
 		$sso_url = trailingslashit( $url ) . 'sso/verify';
 	} else {
 		// If we hit a protected page, OR a subsite, log to the main site / root, then redirect to that page/subsite
-		// This doesn't work with protected pages in a sub-directory installs, ie anything outside of wp-admin there
-		// as we cannot detect the site home URL!
-		$sso_url = str_replace( $path, '/sso/verify', $url );
+		$sso_url = get_site_url( get_blog_id( $url ), '/sso/verify' );
 	}
 
 	$sso_url = add_query_arg( 'redirect_to', $url, $sso_url );
```
Comment (roborourke) [inline inc/namespace.php:658]:
```suggestion
	$sso_url = add_query_arg( 'redirect_to', urlencode( $url ), $sso_url );
```
